spring:
  application:
    name: deposito
  profiles:
    active: desenvolvimento
  thymeleaf:
    check-template-location: false

    spring:
      datasource:
        url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
        username: rm99741
        password: 080802
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

server:
  port: 80


